services:
  - type: web
    runtime: node
    name: bestillingssystem-kino
    repo: https://github.com/issim9825/Bestillingssystem-kino
    region: frankfurt
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
