services:
  - type: web
    name: my-spring-app
    env: java
    plan: free
    buildCommand: |
      chmod +x mvnw
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
