CREATE TABLE BILLETT
(
    ID SMALLINT AUTO_INCREMENT NOT NULL,
    FILM VARCHAR(50) NOT NULL,
    ANTALL INTEGER NOT NULL,
    FNAVN VARCHAR(50) NOT NULL,
    ENAVN VARCHAR(50) NOT NULL,
    TLFNR CHAR(8) NOT NULL,
    EPOST VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

