CREATE TABLE BILLETT
(
    FILM VARCHAR(50) NOT NULL,
    ANTALL INTEGER NOT NULL,
    FNAVN VARCHAR(50) NOT NULL,
    ENAVN VARCHAR(50) NOT NULL,
    TLFNR CHAR(8) NOT NULL,
    EPOST VARCHAR(50) NOT NULL
);
